### ISSUE TITLE
Store the Ciphertext in a separate file.

### ISSUE THREAD

**Issue by lucasvieirasilva** [lucasvieirasilva/aws-ssm-secrets-cli#25]
Currently, the ciphertext values are stored in the main config YAML file, which makes the config YAML difficult to read.

Example:
```yaml
parameters:
- name: /myparam
  type: SecureString
  value: AQICAHih8NMGYtE...
```

#### Proposal

For the SSM Parameter SecureString and AWS Secrets store the ciphertext value in a different file with the same name of the YAML file in the same folder with `*.secret.yaml` naming convention.

So, the config YAML file will be:

```yaml
parameters:
- name: /myparam
  type: SecureString
```

And the `*.secret.yaml` file will be:

```yaml
parameters:
- name: /myparam
   value: AQICAHih8NMGYtE...
```
