### ISSUE TITLE
Add namespaces section in the SSM/Secrets

### ISSUE THREAD

**Issue by lucasvieirasilva** [lucasvieirasilva/aws-ssm-secrets-cli#29]
Currently, the AWS Secrets CLI organizes the configuration file as a flat list of the SSM parameters and AWS Secrets Manager secrets.

```yaml
- name: /dev/service1/password
  type: SecureString
  description: "Service 1 Password"
- name: /dgx/service2/api-key
  type: SecureString
  description: "Service 2 API Key"
- name: /dgx/service1/private-key
  type: SecureString
  description: "Service 2 Private Key"
```

When there are a lot of entries in the configuration file and you add a new ssm for the same namespace the entry will be at the end of the file, which is not good for reading.

#### Proposal

Create a new section in the `parameters` and `secrets` named `namespace` and organize the levels of the entries based on the object structure.

Example:

```yaml
parameters:
  namespace:
    # /dev
    dev:
      # /dev/service1
      service1:
        # /dev/service1/password
        password:
          type: SecureString
          description: "Service 1 Password"
        # /dev/service1/private-key
        private-key:
          type: SecureString
          description: "Service 2 Private Key"
      # /dev/service2
      service2:
        # /dev/service2/api-key
        api-key:
          type: SecureString
          description: "Service 2 API Key"
```
