### ISSUE TITLE
CLI fails when deploying a secret to a region where the KMS key was not created.

### ISSUE THREAD

**Issue by plinioh** [lucasvieirasilva/aws-ssm-secrets-cli#54]
With a KMS key created in `us-east-1`, when trying to create a new secret in `sa-east-1`, for example:

config.yaml
```yaml
encryption_sdk: aws_encryption_sdk
kms:
  arn: !cf_output "aws-secrets-kms.KeyArn"
parameters: []
secrets:
  - description: plinio-test
    name: test/plinio
secrets_file: ./secrets/audit.secrets.yaml
```

Launching in `us-east-1` (Region where `aws-secrets-kms` CloudFormation stack is actually created):
```bash
aws-secrets set-secret --env-file accout.yaml --profile my-profil --region us-east-1 --name test/plinio --description "plinio-test"
Enter/Paste your secret. Ctrl-D or Ctrl-Z ( windows ) to save it.
```

Launching in `sa-east-1`:
```bash
aws-secrets set-secret --env-file accout.yaml --profile my-profile --region sa-east-1 --name test/plinio --description "plinio-test"
[2023-09-05 13:07:58] - An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id aws-secrets-kms does not exist
```

Possible fix:

Make so that the yaml tag `!cf_output` also accepts the pattern `<stack-name>.<output-name>.<aws-region>`, so that the `config.yaml` file would look like:

```yaml
encryption_sdk: aws_encryption_sdk
kms:
  arn: !cf_output "aws-secrets-kms.KeyArn.us-east-1"
parameters: []
secrets:
  - description: plinio-test
    name: test/plinio
secrets_file: ./secrets/audit.secrets.yaml
```
