### ISSUE TITLE
Add "region" property to both parameters and secrets.

### ISSUE THREAD

**Issue by plinioh** [lucasvieirasilva/aws-ssm-secrets-cli#60]
# Issue

Currently the CLI infers the AWS region a secret or parameter will be created on by the `--region` flag when running `aws-secrets deploy ...`. For example, a config file:

aws-account-1.yaml
```yaml
encryption_sdk: aws_encryption_sdk
kms:
  arn: !cf_output "aws-secrets-kms.KeyArn"
parameters: []
secrets:
  - description: a good description
    name: secret/one
secrets_file: ./secrets/aws-account-1.yaml.secrets.yaml
```

Running the command bellow will create the secret `secret/one` in `us-east-1` on `aws-account-1` account.
```bash
aws-secrets deploy -e aws-account-1.yaml --profile aws-account-1 --region us-east-1
```
But if we instead ran this command, the same secret would also be created in `us-west-1`:
```bash
aws-secrets deploy -e aws-account-1.yaml --profile aws-account-1 --region us-west-1
```

This current behavior makes it impossible to have secrets from multiple regions in the AWS account (and by extrapolation the same configuration file).

# Proposed Solution

Have `region` be a property of every secret and parameter:

```yaml
encryption_sdk: aws_encryption_sdk
kms:
  arn: !cf_output "aws-secrets-kms.KeyArn.us-east-1"
parameters: []
secrets:
  - name: secret/one    
    region: us-west-1
  -  name: secret/two
    region: sa-east-1
  - name: secret/three
    region: us-east-1
secrets_file: ./secrets/aws-account-1.yaml.secrets.yaml
tags:
  managed-by: aws-secrets
```

This would require some breaking changes in the CLI, as `region` would be a required CLI option (the already existent `--region`) when creating a secret or parameter.

For users that only use a single region, we could simplify this by adding a `default_region` property as:

```yaml
encryption_sdk: aws_encryption_sdk
default_region: us-east-1
kms:
  arn: !cf_output "aws-secrets-kms.KeyArn.us-east-1"
parameters: []
secrets:
  - name: secret/one    # the region for this secret would be `default_region` (us-east-1)
secrets_file: ./secrets/aws-account-1.yaml.secrets.yaml
tags:
  managed-by: aws-secrets
```
